第１３課題（最終課題）提出
akitoc342/lecture pull request #17
Opened 2023-05-06 13:08 UTC by akitoc342

テスト

2023-05-06 17:05 UTC, MasatoshiMizumoto commented
厳格にしている現場があると良くないのでお伝えしておきますが、ブランチ名は現場に入ったら英字にしてくださいね！

2023-05-06 17:10 UTC, MasatoshiMizumoto requested changes
コメント入れた部分ご対応いただければ他はOKです！

2023-05-06 17:10 UTC, MasatoshiMizumoto commented on cloudformationymlfile/lecture10vpc.yml
空行警告出てるので解消しておいてください！

2023-05-06 17:10 UTC, MasatoshiMizumoto commented on README.md
ポートフォリオにしていくなら、各行はリンクにして各ファイルに飛べるようにするのが良いかもですね！

2023-05-06 23:48 UTC, closed without merging

2023-05-07 01:50 UTC, akitoc342 commented
指摘して頂いた場所を修正しました。https://github.com/akitoc342/lecture/commit/2dfe809353296be0cbd4b1011587bf39d27c9379  
(branch名変更して反映したらプルリクエストに反映されなくなってしまったので、リンクで失礼します。)
確認お願い致します。